# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs:
  - python
  - py-torch
  - py-lightning
  - py-scipy
  - py-torchvision
  - py-pillow
  - py-h5py
  - py-pandas
  - py-scikit-learn
  - py-matplotlib
  - py-pip
  - py-kosh
  - py-mpi4py
  - faiss
  - caliper
  - redis-plus-plus
  - amqp-cpp +tcp
  - py-pika
  # - jeds-cli # leads to issues with Rust
  - nlohmann-json
  - openmpi
  view: false
  concretizer:
    unify: true
    reuse: false
  env_vars:
    set:
      CARGO_HTTP_CHECK_REVOKE: "false" # Cargo can fail due to certificate
  repos:
    llnl_ams: ../repo/spack_repo/llnl_ams
  packages:
    all:
      variants: +cuda~rocm cuda_arch=90
    cub:
      externals:
        - spec: cub@2.2008.2
          prefix: /usr/local/cuda
      buildable: false
    cudnn:
      require: "@8.9.7.29-12"
    mpi:
      require: [openmpi]
    blas: 
      require: [openblas]
    lapack: 
      require: [openblas]
    # zlib-ng is tricky to build so we avoid it
    zlib-ng:
      require: [zlib]
    # Turn off valgrind. Add mkl back in if using intel
    py-torch:
      require: '@2.7~valgrind~mkldnn+distributed+mpi+cudnn+nccl+kineto~xnnpack'
    # Faiss needs python bindings.
    faiss:
      require: +python+shared+cuda build_system=cmake
    # Redis needs tls, and we're using this cxx std.
    redis-plus-plus:
      require: '@1.3+tls cxxstd=14'
    py-tqdm:
      require: ~notebook
    # We need caliper shared, and the caliper package has silly defaults.
    # Turn off the finicky dependencies that caused compilation issues.
    # caliper master: 9818904bb71171779df5e47fee5a5c57c035698f
    caliper:
      require: '@master +shared~libdw~libunwind~papi cuda_arch=90'
    # Need to fix bug in certipy for jeds-cli
    py-pyopenssl:
      require: "@23.2.0:"
    # Match install on Tuo
    openssl:
      require: "@3.4.1"
    # Using api=v18 by default for visit compat.
    hdf5:
      require: '@1.14~mpi api=v18'
    # need to freeze eigen for reproducibility.
    eigen:
      require: '@git.ac3ef16f30b7708a3c6c39b964e1f294dd16b8a3=master'
    cmake:
      require: '@3.26:'
