function(ADD_WORKFLOW_UNIT_TEST name exec)
  string(JOIN " " args ${ARGN})
  add_test(NAME ${name} COMMAND bash -c "rm -f ${CMAKE_CURRENT_BINARY_DIR}/db_label*.h5; ${exec} ${args}")
  set_tests_properties(${name} PROPERTIES LABELS WORKFLOW_UNIT_TEST)
endfunction()

function(BUILD_UNIT_TEST exe source)
  add_executable(${exe} ${source})

  target_include_directories(${exe} PRIVATE ${CMAKE_SOURCE_DIR}/src/AMSlib/)
  target_include_directories(${exe} PRIVATE ${CMAKE_BINARY_DIR}/include/)
  target_link_libraries(${exe} PRIVATE ${AMS_APP_LIBRARIES} stdc++fs AMS torch)

  if (WITH_HDF5)
    target_link_libraries(${exe} PRIVATE ${AMS_HDF5_TARGET})
  endif()
  target_compile_definitions(${exe} PRIVATE ${AMS_APP_DEFINES})

  if(WITH_CUDA)
    target_link_libraries(${exe} PRIVATE CUDA::cudart)
    target_compile_definitions(${exe} PRIVATE "-D__ENABLE_CUDA__ -DLIBAMS_VERBOSE")
  endif()
endfunction()

function(ADD_HDF5_UNIT_TEST name exec)
  add_test(NAME ${name} COMMAND ${exec} ${ARGN})
  set_tests_properties(${name} PROPERTIES LABELS WORKFLOW_UNIT_TEST)
endfunction()

BUILD_UNIT_TEST(domain_to_application domain_to_application.cpp)
BUILD_UNIT_TEST(subselect_tensors subselect_tensors.cpp)
BUILD_UNIT_TEST(scatter_physics scatter_physics.cpp)
BUILD_UNIT_TEST(evaluate_in_and_outs evaluate_in_and_outs.cpp)

ADD_WORKFLOW_UNIT_TEST(WORKFLOW::HOST::DomainToApplication::FLOAT::FLOAT domain_to_application float float cpu)
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::HOST::DomainToApplication::DOUBLE::FLOAT domain_to_application double float cpu)
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::HOST::DomainToApplication::FLOAT::DOUBLE domain_to_application float double cpu)
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::HOST::DomainToApplication::DOUBLE::DOUBLE domain_to_application double double cpu)

ADD_WORKFLOW_UNIT_TEST(WORKFLOW::HOST::SubSelect::Double subselect_tensors double cpu)
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::HOST::SubSelect::Float subselect_tensors float cpu)

ADD_WORKFLOW_UNIT_TEST(WORKFLOW::HOST::ScatterPhysics::Double scatter_physics double cpu)
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::HOST::ScatterPhysics::Float scatter_physics float cpu)

ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InAndOuts::PhFloat::MLFloat::AllPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InInoutsAndOuts::PhFloat::MLFloat::AllPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 0.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::Inouts::PhFloat::MLFloat::AllPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InAndOuts::PhFloat::MLDouble::AllPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InInoutsAndOuts::PhFloat::MLDouble::AllPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 0.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::Inouts::PhFloat::MLDouble::AllPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InAndOuts::PhDouble::MLDouble::AllPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InInoutsAndOuts::PhDouble::MLDouble::AllPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 0.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::Inouts::PhDouble::MLDouble::AllPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InAndOuts::PhDouble::MLFloat::AllPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InInoutsAndOuts::PhDouble::MLFloat::AllPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 0.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::Inouts::PhDouble::MLFloat::AllPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")

ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InAndOuts::PhFloat::MLFloat::BothModelPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InInoutsAndOuts::PhFloat::MLFloat::BothModelPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 0.5 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::Inouts::PhFloat::MLFloat::BothModelPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InAndOuts::PhFloat::MLDouble::BothModelPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InInoutsAndOuts::PhFloat::MLDouble::BothModelPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 0.5 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::Inouts::PhFloat::MLDouble::BothModelPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InAndOuts::PhDouble::MLDouble::BothModelPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InInoutsAndOuts::PhDouble::MLDouble::BothModelPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 0.5 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::Inouts::PhDouble::MLDouble::BothModelPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InAndOuts::PhDouble::MLFloat::BothModelPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InInoutsAndOuts::PhDouble::MLFloat::BothModelPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 0.5 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::Inouts::PhDouble::MLFloat::BothModelPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")

ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InAndOuts::PhFloat::MLFloat::AllModel evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InInoutsAndOuts::PhFloat::MLFloat::AllModel evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 1.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::Inouts::PhFloat::MLFloat::AllModel evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InAndOuts::PhFloat::MLDouble::AllModel evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InInoutsAndOuts::PhFloat::MLDouble::AllModel evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 1.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::Inouts::PhFloat::MLDouble::AllModel evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InAndOuts::PhDouble::MLDouble::AllModel evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InInoutsAndOuts::PhDouble::MLDouble::AllModel evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 1.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::Inouts::PhDouble::MLDouble::AllModel evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_cpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InAndOuts::PhDouble::MLFloat::AllModel evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::InInoutsAndOuts::PhDouble::MLFloat::AllModel evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 1.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLHost::Evaluate::Inouts::PhDouble::MLFloat::AllModel evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_cpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")

if (WITH_CUDA)
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::DEVICE::DomainToApplication::FLOAT::FLOAT domain_to_application float float cuda)
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::DEVICE::DomainToApplication::DOUBLE::FLOAT domain_to_application double float cuda)
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::DEVICE::DomainToApplication::FLOAT::DOUBLE domain_to_application float double cuda)
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::DEVICE::DomainToApplication::DOUBLE::DOUBLE domain_to_application double double cuda)

ADD_WORKFLOW_UNIT_TEST(WORKFLOW::DEVICE::SubSelect::Double subselect_tensors double cuda)
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::DEVICE::SubSelect::Float subselect_tensors float cuda)

ADD_WORKFLOW_UNIT_TEST(WORKFLOW::DEVICE::ScatterPhysics::Double scatter_physics double cuda)
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::DEVICE::ScatterPhysics::Float scatter_physics float cuda)


ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InAndOuts::PhFloat::MLFloat::AllPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InInoutsAndOuts::PhFloat::MLFloat::AllPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::Inouts::PhFloat::MLFloat::AllPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InAndOuts::PhFloat::MLDouble::AllPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InInoutsAndOuts::PhFloat::MLDouble::AllPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::Inouts::PhFloat::MLDouble::AllPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InAndOuts::PhDouble::MLDouble::AllPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InInoutsAndOuts::PhDouble::MLDouble::AllPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::Inouts::PhDouble::MLDouble::AllPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InAndOuts::PhDouble::MLFloat::AllPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InInoutsAndOuts::PhDouble::MLFloat::AllPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::Inouts::PhDouble::MLFloat::AllPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InAndOuts::PhFloat::MLFloat::AllPhysics evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InInoutsAndOuts::PhFloat::MLFloat::AllPhysics evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::Inouts::PhFloat::MLFloat::AllPhysics evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InAndOuts::PhFloat::MLDouble::AllPhysics evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InInoutsAndOuts::PhFloat::MLDouble::AllPhysics evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::Inouts::PhFloat::MLDouble::AllPhysics evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InAndOuts::PhDouble::MLDouble::AllPhysics evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InInoutsAndOuts::PhDouble::MLDouble::AllPhysics evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::Inouts::PhDouble::MLDouble::AllPhysics evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InAndOuts::PhDouble::MLFloat::AllPhysics evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InInoutsAndOuts::PhDouble::MLFloat::AllPhysics evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::Inouts::PhDouble::MLFloat::AllPhysics evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")

ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InAndOuts::PhFloat::MLFloat::BothModelPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InInoutsAndOuts::PhFloat::MLFloat::BothModelPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.5 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::Inouts::PhFloat::MLFloat::BothModelPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InAndOuts::PhFloat::MLDouble::BothModelPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InInoutsAndOuts::PhFloat::MLDouble::BothModelPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.5 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::Inouts::PhFloat::MLDouble::BothModelPhysics evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InAndOuts::PhDouble::MLDouble::BothModelPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InInoutsAndOuts::PhDouble::MLDouble::BothModelPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.5 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::Inouts::PhDouble::MLDouble::BothModelPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InAndOuts::PhDouble::MLFloat::BothModelPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InInoutsAndOuts::PhDouble::MLFloat::BothModelPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.5 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::Inouts::PhDouble::MLFloat::BothModelPhysics evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InAndOuts::PhFloat::MLFloat::BothModelPhysics evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InInoutsAndOuts::PhFloat::MLFloat::BothModelPhysics evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.5 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::Inouts::PhFloat::MLFloat::BothModelPhysics evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InAndOuts::PhFloat::MLDouble::BothModelPhysics evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InInoutsAndOuts::PhFloat::MLDouble::BothModelPhysics evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.5 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::Inouts::PhFloat::MLDouble::BothModelPhysics evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InAndOuts::PhDouble::MLDouble::BothModelPhysics evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InInoutsAndOuts::PhDouble::MLDouble::BothModelPhysics evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.5 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::Inouts::PhDouble::MLDouble::BothModelPhysics evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InAndOuts::PhDouble::MLFloat::BothModelPhysics evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InInoutsAndOuts::PhDouble::MLFloat::BothModelPhysics evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.5 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::Inouts::PhDouble::MLFloat::BothModelPhysics evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 0.5  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")

ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InAndOuts::PhFloat::MLFloat::AllModel evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InInoutsAndOuts::PhFloat::MLFloat::AllModel evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 1.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::Inouts::PhFloat::MLFloat::AllModel evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InAndOuts::PhFloat::MLDouble::AllModel evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InInoutsAndOuts::PhFloat::MLDouble::AllModel evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 1.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::Inouts::PhFloat::MLDouble::AllModel evaluate_in_and_outs float cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InAndOuts::PhDouble::MLDouble::AllModel evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InInoutsAndOuts::PhDouble::MLDouble::AllModel evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 1.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::Inouts::PhDouble::MLDouble::AllModel evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InAndOuts::PhDouble::MLFloat::AllModel evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::InInoutsAndOuts::PhDouble::MLFloat::AllModel evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 1.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhHOST::MLDevice::Evaluate::Inouts::PhDouble::MLFloat::AllModel evaluate_in_and_outs double cpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InAndOuts::PhFloat::MLFloat::AllModel evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InInoutsAndOuts::PhFloat::MLFloat::AllModel evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 1.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::Inouts::PhFloat::MLFloat::AllModel evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InAndOuts::PhFloat::MLDouble::AllModel evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InInoutsAndOuts::PhFloat::MLDouble::AllModel evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 1.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::Inouts::PhFloat::MLDouble::AllModel evaluate_in_and_outs float gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InAndOuts::PhDouble::MLDouble::AllModel evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InInoutsAndOuts::PhDouble::MLDouble::AllModel evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 1.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::Inouts::PhDouble::MLDouble::AllModel evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/double_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InAndOuts::PhDouble::MLFloat::AllModel evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "0")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::InInoutsAndOuts::PhDouble::MLFloat::AllModel evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 1.0 "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "1")
ADD_WORKFLOW_UNIT_TEST(WORKFLOW::PhDevice::MLDevice::Evaluate::Inouts::PhDouble::MLFloat::AllModel evaluate_in_and_outs double gpu ${TORCH_MODEL_DIR}/single_gpu_duq_max.pt "duq_max" 1.0  "1,8" "1,8" ${CMAKE_CURRENT_BINARY_DIR}/ "8")

endif()

