[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ams-wf"
version = "1.0"
requires-python = ">=3.10"
maintainers = [
    { name = "Konstantinos Parasyris", email = "parasyris1@llnl.gov" },
    { name = "Loic Pottier", email = "pottier1@llnl.gov" },
    { name = "Robert C. Blake", email = "blake14@llnl.gov" },
]
authors = [
    { name = "Harsh Bhatia", email = "hbhatia@llnl.gov" },
    { name = "Tapasya A. Patki", email = "patki1@llnl.gov" },
    { name = "Stephanie Brink", email = "brink2@llnl.gov" },
    { name = "Loic Pottier", email = "pottier1@llnl.gov" },
    { name = "Thomas M. Stitt", email = "stitt4@llnl.gov" },
    { name = "Konstantinos Parasyris", email = "parasyris1@llnl.gov" },
    { name = "Daniel J. Milroy", email = "milroy1@llnl.gov" },
    { name = "Daniel E. Laney", email = "laney1@llnl.gov" },
    { name = "Robert C. Blake", email = "blake14@llnl.gov" },
    { name = "Jae-Seung Yeom", email = "yeom2@llnl.gov" },
    { name = "Peer-Timo Bremer", email = "bremer5@llnl.gov" },
    { name = "Charles Doutriaux", email = "doutriaux1@llnl.gov" },
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
  "h5py",
  "argparse",
  "SQLAlchemy",
  "mysql-connector-python",
  "pika>=1.3.0",
  "numpy>=1.2.0",
  "flux-python>=0.75.0"
]

[project.optional-dependencies]
dev = [
  "ruff",
]

[project.scripts]
AMSBroker = "ams_wf.AMSBroker:main"
AMSDBStage = "ams_wf.AMSDBStage:main"
AMSOrchestrator = "ams_wf.AMSOrchestrator:main"
AMSStore = "ams_wf.AMSStore:main"
AMSTrain = "ams_wf.AMSTrain:main"
AMSDeploy = "ams_wf.AMSDeploy:main"

[project.urls]
"Homepage" = "https://github.com/LLNL/AMS/"

[tool.setuptools]
package-dir = {"" = "src/AMSWorkflow"}
packages = ["ams_wf", "ams"]

# E501: Line too long
# W503: Line break occurred before binary operator
# E226: Missing white space around arithmetic operator
[tool.ruff]
line-length = 120
show-fixes = true
exclude = [
  ".git",
  "__pycache__",
  "*.egg-info",
  "build"
]

[tool.ruff.lint]
select = ['E', 'F', 'W', 'A', 'PLC', 'PLE', 'PLW', 'I', 'N', 'Q', 'B', 'UP', 'SIM', 'RUF']
ignore = ["E501", "E226", "E203"]

[tool.ruff.lint.isort]
known-first-party = ["ams", "ams_wf"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

