/*
 * Copyright 2021-2023 Lawrence Livermore National Security, LLC and other
 * AMSLib Project Developers
 *
 * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 */

#ifndef __AMS_WORKFLOW_HPP__
#define __AMS_WORKFLOW_HPP__

#include <c10/core/DeviceType.h>

#include <memory>
#include <stdexcept>

#include "debug.h"
#ifdef __AMS_ENABLE_CALIPER__
#include <caliper/cali_macros.h>
#endif

#include <ATen/core/TensorBody.h>

#include "AMS.h"
#include "ml/surrogate.hpp"
#include "resource_manager.hpp"
#include "util/ArrayRef.hpp"
#include "util/SmallVector.hpp"
#include "wf/basedb.hpp"

#ifdef __ENABLE_MPI__
#include <mpi.h>

#include "wf/redist_load.hpp"
#endif

#include "wf/debug.h"

//! ----------------------------------------------------------------------------
//! AMS Workflow class
//! the purpose of this class is to expose an "evaluate" function
//!     which has the same interface as the physics evaluation
//! the intention is that we can easily switch in and out AMS wf in app code
//! ----------------------------------------------------------------------------
namespace ams
{
class AMSWorkflow
{

  /** @brief The application call back to perform the original SPMD physics
     * execution */
  AMSPhysicFn AppCall;

  /** @brief A string identifier describing the domain-model being solved. */
  std::string domainName;

  /** @brief A string used as a prefix of the filename generated by the Database manager **/
  std::string dbLabel;

  /** @brief The module that performs uncertainty quantification (UQ) */
  std::shared_ptr<SurrogateModel> MLModel;

  /** The metric/type of UQ we will use to select between physics and ml computations **/
  const AMSUQPolicy uqPolicy = AMSUQPolicy::AMS_UQ_END;

  /** @brief The database to store data for which we cannot apply the current
     * model */
  std::shared_ptr<ams::db::BaseDB> DB;

  /** @brief The process id. For MPI runs this is the rank */
  const int rId;

  /** @brief The total number of processes participating in the simulation
     * (world_size for MPI) */
  int wSize;

  /** @brief  Location of the original application data  (CPU or GPU) */
  AMSResourceType appDataLoc;

  /** @brief execution policy of the distributed system. Load balance or not. */
  AMSExecPolicy ePolicy;


  /** @brief The maximum distance of the predicate for a sample prediction to be considered as valid **/
  const float threshold;

#ifdef __ENABLE_MPI__
  /** @brief MPI Communicator for all ranks that call collectively the evaluate function **/
  MPI_Comm comm;
#endif

  /** @brief Is the evaluate a distributed execution **/
  bool isDistributed;

  /** \brief Store the data in the database and copies
     * data from the GPU to the CPU and then to the database.
     * To store GPU resident data we use a 1MB of "pinned"
     * memory as a buffer
     * @param[in] num_elements Number of elements of each 1-D vector
     * @param[in] inputs vector to 1-D vectors storing num_elements
     * items to be stored in the database
     * @param[in] outputs vector to 1-D vectors storing num_elements
     * items to be stored in the database
     */
  void store(ArrayRef<torch::Tensor> Inputs, ArrayRef<torch::Tensor> Outputs)
  {
    if (!DB) return;

    c10::SmallVector<torch::Tensor> ConvertedInputs(Inputs.begin(),
                                                    Inputs.end());
    c10::SmallVector<torch::Tensor> ConvertedOutputs(Outputs.begin(),
                                                     Outputs.end());
    auto Input = torch::cat(ConvertedInputs, Inputs[0].sizes().size() - 1);
    auto Output = torch::cat(ConvertedOutputs, Outputs[0].sizes().size() - 1);
    // No database, so just de-allocate and return
    if (appDataLoc == AMSResourceType::AMS_HOST) {
      return DB->store(Input, Output);
    }
    if (Input.device() == c10::DeviceType::CUDA) Input = Input.cpu();
    if (Output.device() == c10::DeviceType::CUDA) Output = Output.cpu();

    // Store to database
    DB->store(Input, Output);

    return;
  }

  /** \brief Check if we can perform a surrogate model update.
     *  AMS can update surrogate model only when all MPI ranks have received 
     * the latest model from RabbitMQ.
     * @return True if surrogate model can be updated
     */
  bool updateModel()
  {
    if (!DB || !DB->allowModelUpdate()) return false;
    bool local = DB->updateModel();
#ifdef __ENABLE_MPI__
    bool global = false;
    MPI_Allreduce(&local, &global, 1, MPI_CXX_BOOL, MPI_LAND, comm);
    return global;
#else
    return local;
#endif
  }

public:
  AMSWorkflow(AMSPhysicFn _AppCall,
              std::string &surrogate_path,
              std::string &domain_name,
              std::string &db_label,
              bool isDebugDB,
              AMSResourceType app_data_loc,
              float threshold,
              const AMSUQPolicy uq_policy,
              int _pId = 0,
              int _wSize = 1)
      : AppCall(_AppCall),
        domainName(domain_name),
        dbLabel(db_label),
        rId(_pId),
        wSize(_wSize),
        appDataLoc(app_data_loc),
        uqPolicy(uq_policy),
#ifdef __ENABLE_MPI__
        comm(MPI_COMM_NULL),
#endif
        threshold(threshold),
        ePolicy(AMSExecPolicy::AMS_UBALANCED)
  {
    DB = nullptr;
    auto &dbm = ams::db::DBManager::getInstance();

    DB = dbm.getDB(domainName, dbLabel, rId);
    MLModel = nullptr;
    if (!surrogate_path.empty())
      MLModel = SurrogateModel::getInstance(surrogate_path);
  }

  void set_physics(AMSPhysicFn _AppCall) { AppCall = _AppCall; }

#ifdef __ENABLE_MPI__
  void set_communicator(MPI_Comm communicator) { comm = communicator; }
#endif

  void set_exec_policy(AMSExecPolicy policy) { ePolicy = policy; }

  bool should_load_balance() const
  {
#ifdef __ENABLE_MPI__
    return (comm != MPI_COMM_NULL && ePolicy == AMSExecPolicy::AMS_BALANCED);
#else
    return false;
#endif
  }


  static SmallVector<at::Tensor> subSelectTensors(ArrayRef<at::Tensor> Tensors,
                                                  at::Tensor &Mask)
  {
    SmallVector<at::Tensor> NewVector;
    for (auto O : Tensors) {
      NewVector.push_back(O.index({Mask}));
    }
    return NewVector;
  }

  static void ScatterPhysicOutputsToOrigDomain(
      ArrayRef<at::Tensor> ComputedTensors,
      torch::Tensor &Predicate,
      ArrayRef<torch::Tensor> AppTensors)
  {
    if (ComputedTensors.size() != AppTensors.size()) {
      throw std::runtime_error(
          "Expecting equal sized tensors when composing Original and domain "
          "memories\n");
    }
    for (int i = 0; i < ComputedTensors.size(); i++) {
      AppTensors[i].masked_scatter_(Predicate, ComputedTensors[i]);
    }
  }


  static int MLDomainToApplication(at::Tensor Src,
                                   MutableArrayRef<at::Tensor> Dest,
                                   at::Tensor Predicate,
                                   int offset)
  {
    int outerDim = Src.dim() - 1;
    for (auto &dst : Dest) {
      int ConcatAxisSize = dst.sizes()[dst.dim() - 1];
      at::Tensor Slice =
          Src.narrow(outerDim, offset, ConcatAxisSize).to(dst.options());
      dst.index_put_({Predicate}, Slice.index({Predicate}));
      offset += ConcatAxisSize;
    }
    return offset;
  }


  ~AMSWorkflow() { DBG(Workflow, "Destroying Workflow Handler"); }

  /** @brief This is the main entry point of AMSLib and replaces the original
     * execution path of the application.
     * @param[in] probDescr an opaque type that will be forwarded to the
     * application upcall
     * @param[in] totalElements the total number of elements to apply the SPMD
     * function on
     * @param[in] inputs the inputs of the computation.
     * @param[out] outputs the computed outputs.
     * @param[in] Comm The MPI Communicatotor for all ranks participating in the
     * SPMD execution.
     *
     * @details The function corresponds to the main driver of the AMSLib.
     * Assuming an original 'foo' function void foo ( void *cls, int numElements,
     * void **inputs, void **outputs){ parallel_for(I : numElements){
     *       cls->physics(inputs[0][I], outputs[0][I]);
     *    }
     * }
     *
     * The AMS transformation would functionaly look like this:
     * void AMSfoo ( void *cls, int numElements, void **inputs, void **outputs){
     *    parallel_for(I : numElements){
     *       if ( UQ (I) ){
     *          Surrogate(inputs[0][I], outputs[0][I])
     *       }
     *       else{
     *        cls->physics(inputs[0][I], outputs[0][I]);
     *        DB->Store(inputs[0][I], outputs[0][I]);
     *       }
     *    }
     * }
     *
     * Yet, AMS assumes a SPMD physics function (in the example cls->physics).
     * Therefore, the AMS transformation is taking place at the level of the SPMD
     * execution. The following transformation is equivalent void AMSfoo( void
     * *cls, int numElements, void **inputs, void **outputs){ predicates =
     * UQ(inputs, numElements); modelInputs, physicsInputs = partition(predicates,
     * inputs); modelOuputs, physicsOutputs = partition(predicates, output);
     *    foo(cls, physicsInputs.size(), physicsInputs, physicsOutputs);
     *    surrogate(modelInputs, modelOuputs, modelOuputs.size());
     *    DB->Store(physicsInputs, physicsOutputs);
     *    concatenate(outptuts, modelOuputs, predicate);
     * }
     *
     * This transformation can exploit the parallel nature of all the required
     * steps.
     */
  void evaluate(void *probDescr,
                ams::MutableArrayRef<at::Tensor> Ins,
                ams::MutableArrayRef<at::Tensor> InOuts,
                ams::MutableArrayRef<at::Tensor> Outs)
  {
    CALIPER(CALI_MARK_BEGIN("AMSEvaluate");)

    SmallVector<at::Tensor> InputTensors(Ins.begin(), Ins.end());
    SmallVector<at::Tensor> OutputTensors(Ins.begin(), Ins.end());
    for (auto Tensor : InOuts) {
      InputTensors.push_back(Tensor);
      OutputTensors.push_back(Tensor);
    }

    // Here we create a copy of the inputs/outputs. This is "necessary". To correctly handle
    // input-output cases and to also to set them to right precision.

    REPORT_MEM_USAGE(Workflow, "Start")

    if (!MLModel) {
      // FIXME This needs to be updated accordingly and call the new interface.
      throw std::runtime_error("Pending implementation\n");
    }

    CALIPER(CALI_MARK_BEGIN("UPDATEMODEL");)
    if (updateModel()) {
      auto model = DB->getLatestModel();
      CINFO(Workflow,
            rId == 0,
            "Updating surrogate model with %s",
            model.c_str())
      // UQModel->updateModel(model);
    }
    CALIPER(CALI_MARK_END("UPDATEMODEL");)

    // -------------------------------------------------------------
    // STEP 1: call the ML Model to get both the prediction and the predicates.
    // -------------------------------------------------------------
    CALIPER(CALI_MARK_BEGIN("SURROGATE");)
    // The predicate with which we will split the data on a lateMLInputsr step
    auto [MLOutputs, Predicate] =
        MLModel->evaluate(InputTensors, uqPolicy, threshold);

    CALIPER(CALI_MARK_END("SURROGATE");)

    //Copy out the results of the ML Model to the correct indices, this needs to happen
    CALIPER(CALI_MARK_BEGIN("MLDomainToApplication");)
    int offset = MLDomainToApplication(MLOutputs, Outs, Predicate, 0);
    MLDomainToApplication(MLOutputs, InOuts, Predicate, offset);
    CALIPER(CALI_MARK_END("MLDomainToApplication");)


    if (Predicate.sum().item<int64_t>() == 0) return;

    // Revert pedicates and use it to pick the Physic points outputs.
    auto WrongMLIndices = torch::logical_not(Predicate);

    // Physis* tensors have the points which the model could not accurately predict
    CALIPER(CALI_MARK_BEGIN("PACK");)
    SmallVector<at::Tensor> PhysicIns(subSelectTensors(Ins, WrongMLIndices));
    SmallVector<at::Tensor> PhysicInOuts(
        subSelectTensors(InOuts, WrongMLIndices));
    // TODO: Outs does not need sub select, we will write all of these from scratch
    SmallVector<at::Tensor> PhysicOuts(subSelectTensors(Outs, WrongMLIndices));
    CALIPER(CALI_MARK_END("PACK");)

    // Copy and clone. This important to take place before AppCall is executed. To keep a copy of the input values
    // that will be overwritten.
    SmallVector<at::Tensor> PhysicInOutsBefore;
    for (auto S : PhysicInOuts)
      PhysicInOutsBefore.push_back(S.clone());

    // We call the application here
    CALIPER(CALI_MARK_BEGIN("PHYSICS MODULE");)
    //AppCall(probDescr, PhysicIns, PhysicInOuts, PhysicOuts);
#warning put back in when interface is clean.
    CALIPER(CALI_MARK_END("PHYSICS MODULE");)


    CALIPER(CALI_MARK_BEGIN("UNPACK");)
    // Copy out the computation results to the original tensors/buffers
    ScatterPhysicOutputsToOrigDomain(PhysicOuts, WrongMLIndices, Outs);
    ScatterPhysicOutputsToOrigDomain(PhysicInOuts, WrongMLIndices, InOuts);
    CALIPER(CALI_MARK_END("UNPACK");)


    DBG(Workflow, "Finished physics evaluation")

    if (DB) {
      CALIPER(CALI_MARK_BEGIN("DBSTORE");)
      SmallVector<at::Tensor> StoreInputTensors(PhysicIns.begin(),
                                                PhysicIns.end());
      SmallVector<at::Tensor> StoreOutputTensors(PhysicOuts.begin(),
                                                 PhysicOuts.end());
      for (auto Tensor : PhysicInOutsBefore)
        StoreInputTensors.push_back(Tensor);
      for (auto Tensor : PhysicInOuts) {
        StoreOutputTensors.push_back(Tensor);
      }

      DBG(Workflow,
          "Storing data (#elements = %ld) to database",
          StoreInputTensors[0].sizes()[0]);
      store(StoreInputTensors, StoreOutputTensors);
      CALIPER(CALI_MARK_END("DBSTORE");)
    }


    DBG(Workflow, "Finished AMSExecution")
    CINFO(Workflow,
          rId == 0,
          "Computed %ld "
          "using physics out of the %ld items (%.2f)",
          PhysicIns[0].sizes()[0],
          InputTensors[0].sizes()[0],
          (float)(PhysicIns[0].sizes()[0]) / float(InputTensors[0].sizes()[0]));

    REPORT_MEM_USAGE(Workflow, "End")
    CALIPER(CALI_MARK_END("AMSEvaluate");)
  }
};


}  // namespace ams
#endif
