# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs:
  - py-torch
  - nlohmann-json
  - fmt
  - tl-expected
  - hdf5
  - python
  - blt
  - mfem
  - py-lightning
  - py-scipy
  - py-torchvision
  - py-pillow
  - py-h5py
  - py-pandas
  - py-matplotlib
  - py-pip
  - py-mpi4py
  - caliper
  - amqp-cpp +tcp
  - py-pika
  - py-torch-geometric
  - flux-core
  view: true
  concretizer:
    unify: true
    reuse: false
  repos:
    local: ../repo/local/spack_repo/llnl_ams
  packages:
    all:
      variants: [~cuda ~rocm]
      target: [sapphirerapids]
      providers:
        mpi: [openmpi]
        blas: [openblas]
        lapack: [openblas]
    gcc:
      buildable: false
      externals:
      - spec: gcc@13.3.1 languages:="c,c++,fortran"
        prefix: /opt/rh/gcc-toolset-13/root/usr/
        extra_attributes:
          compilers:
            c: /opt/rh/gcc-toolset-13/root/usr/bin/gcc
            cxx: /opt/rh/gcc-toolset-13/root/usr/bin/g++
            fortran: /opt/rh/gcc-toolset-13/root/usr/bin/gfortran
        modules: [gcc/13.3.1]
    mpi:
      buildable: false
      externals:
      - spec: openmpi@4.1.1
        prefix: /usr
        modules: [mpi/openmpi-x86_64]
    py-pandas:
      require: "~performance"
    py-torch:
      require: "@2.9~valgrind~mkldnn+distributed+mpi~cuda~rocm"
    caliper:
      require: "@2.12.1+shared~libdw~libunwind~adiak"
    openblas:
      require: "@0.3.30"
    fmt:
      require: "@11.2.0" # be careful, it must be compatible with the fmt pulled by Torch
    hdf5:
      require: "@2~mpi"
    blt:
      require: "@0.7.1"
    py-pika:
      require: "@1.3.2"
    mfem:
      require: "@4.8~rocm~openmp~cuda+raja~umpire+shared+static~mpi~metis~examples~zlib"
    cmake:
      require: "@3.29.6:"
    # Externals
    automake:
      externals:
      - spec: automake@1.16.1
        prefix: /usr
      buildable: false
    groff:
      externals:
      - spec: groff@1.22.3
        prefix: /usr
      buildable: false
    tar:
      externals:
      - spec: tar@1.30
        prefix: /usr
      buildable: false
    sed:
      externals:
      - spec: sed@4.5
        prefix: /usr
      buildable: false
    bison:
      externals:
      - spec: bison@3.0.4
        prefix: /usr
      buildable: false
    m4:
      externals:
      - spec: m4@1.4.18
        prefix: /usr
      buildable: false
    perl:
      externals:
      - spec: perl@5.26.3~cpanm+opcode~open+shared+threads
        prefix: /usr
    findutils:
      externals:
      - spec: findutils@4.6.0
        prefix: /usr
      buildable: false
    flex:
      externals:
      - spec: flex@2.6.1+lex
        prefix: /usr
      buildable: false
    gawk:
      externals:
      - spec: gawk@4.2.1
        prefix: /usr
      buildable: false
    pkgconf:
      externals:
      - spec: pkgconf@1.4.2
        prefix: /usr
      buildable: false
    openssh:
      externals:
      - spec: openssh@8.0p1
        prefix: /usr
      buildable: false
    autoconf:
      externals:
      - spec: autoconf@2.69
        prefix: /usr
      buildable: false
    openssl:
      externals:
      - spec: openssl@1.1.1k
        prefix: /usr
      buildable: false
    zlib:
      externals:
      - spec: zlib@1.2.11
        prefix: /usr
      buildable: false
    diffutils:
      externals:
      - spec: diffutils@3.6
        prefix: /usr
      buildable: false
    gettext:
      externals:
      - spec: gettext@0.19.8.1
        prefix: /usr
      buildable: false
    gmake:
      externals:
      - spec: gmake@4.2.1
        prefix: /usr
      buildable: false
    curl:
      externals:
      - spec: curl@7.61.1+gssapi+nghttp2
        prefix: /usr
      buildable: false
    coreutils:
      externals:
      - spec: coreutils@8.30
        prefix: /usr
      buildable: false
    binutils:
      externals:
      - spec: binutils@2.40.21~gold~headers
        prefix: /opt/rh/gcc-toolset-13/root/usr
      - spec: binutils@2.30.128~gold~headers
        prefix: /usr
      buildable: false
    git:
      externals:
      - spec: git@2.43.7~tcltk
        prefix: /usr
      buildable: false
    libtool:
      externals:
      - spec: libtool@2.4.6
        prefix: /usr
      buildable: false