mirrors:
  ams_mirror:
    fetch:
      url: file:///usr/workspace/AMS/mirror.spack
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
    push:
      url: file:///usr/workspace/AMS/mirror.spack
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
