name: CI

on:
  # Triggers the workflow on pull request events only for the "develop" branch
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  build-run-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/llnl/ams-ci-almalinux8:latest
      options: --user root

    strategy:
      matrix:
        with_caliper: [ON, OFF]
        with_mpi: [ON, OFF]
        with_torch: [ON, OFF]

    steps:
      - uses: actions/checkout@v7
      - name: Ensure git safe directory
        run: git config --global --add safe.directory '*'
      - name: Build ENABLE_TORCH=${{ matrix.with_torch }} ENABLE_CALIPER=${{ matrix.with_caliper }} ENABLE_MPI=${{ matrix.with_mpi }}
        shell: bash -l {0}
        run: |
          source /etc/profile
          module load gcc/13.3.1 mpi/openmpi-x86_64

          rm -rf build/
          mkdir build
          cd build
          cmake \
            -DBUILD_SHARED_LIBS=On \
            -DCMAKE_INSTALL_PREFIX=./install \
            -DENABLE_CALIPER=${{ matrix.with_caliper }} \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_CUDA=Off \
            -DENABLE_MPI=${{ matrix.with_mpi }} \
            -DENABLE_TESTS=On \
            -DAMS_ENABLE_DEBUG=On \
            -DENABLE_WORKFLOW=Off \
            -DENABLE_TORCH=${{ matrix.with_torch }} \
            -DTorch_DIR=$AMS_TORCH_PATH \
            -Dcaliper_DIR=$AMS_CALIPER_PATH \
            -DAMS_FMT_DIR=$AMS_FMT_DIR \
            -DHDF5_DIR=$AMS_HDF5_PATH \
            -Dnlohmann_json_DIR=$AMS_NLOHMANN_JSON_DIR \
            -Dtl-expected_DIR=$AMS_TL_EXPECTED_DIR \
            -Damqpcpp_DIR=$AMS_AMQPCPP_PATH \
            $GITHUB_WORKSPACE
            make -j$(nproc)
      - name: Run Tests ENABLE_CALIPER=${{ matrix.with_caliper }} ENABLE_MPI=${{ matrix.with_mpi }}
        run: |
          source /etc/profile
          module load gcc/13.3.1 mpi/openmpi-x86_64

          cd build
          # needed otherwise MPI tests will fail when running as root
          if [[ ${{ matrix.with_mpi }} == "ON" ]]; then
            echo "Setting OMP flag to run as root"
            export OMPI_ALLOW_RUN_AS_ROOT=1
            export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
            # needed by blt_mpi_smoke on GitHub CI
            export OMPI_MCA_rmaps_base_oversubscribe=1
          fi
          env CTEST_OUTPUT_ON_FAILURE=1 make test

      - name: Install AMS ENABLE_CALIPER=${{ matrix.with_caliper }} ENABLE_MPI=${{ matrix.with_mpi }}
        run: |
          source /etc/profile
          module load gcc/13.3.1 mpi/openmpi-x86_64

          cd build
          make -j$(nproc) install

  build-cuda-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/llnl/ams-ci-cuda12.9.1:latest
      options: --user root

    strategy:
      matrix:
        with_caliper: [ON, OFF]
        with_mpi: [ON, OFF]
    steps:
      - uses: actions/checkout@v7
      - name: Ensure git safe directory
        run: git config --global --add safe.directory '*'
      - name: Build ENABLE_CUDA=On ENABLE_CALIPER=${{ matrix.with_caliper }} ENABLE_MPI=${{ matrix.with_mpi }}
        shell: bash -l {0}
        run: |
          . /home/ams/venv/bin/activate
          rm -rf build/
          mkdir build
          cd build
          export AMS_INSTALL_PATH=$(pwd)/install
          cmake \
            -DBUILD_SHARED_LIBS=On \
            -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=On \
            -DCMAKE_INSTALL_PREFIX=${AMS_INSTALL_PATH} \
            -DENABLE_CALIPER=${{ matrix.with_caliper }} \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_MPI=${{ matrix.with_mpi }} \
            -DENABLE_TESTS=On \
            -DAMS_ENABLE_DEBUG=On \
            -DENABLE_WORKFLOW=Off \
            -DENABLE_CUDA=On \
            -DTorch_DIR=$AMS_TORCH_PATH \
            -Dcaliper_DIR=$AMS_CALIPER_PATH \
            -DAMS_FMT_DIR=$AMS_FMT_DIR \
            -DHDF5_DIR=$AMS_HDF5_PATH \
            -Dnlohmann_json_DIR=$AMS_NLOHMANN_JSON_DIR \
            -Dtl-expected_DIR=$AMS_TL_EXPECTED_DIR \
            -Damqpcpp_DIR=$AMS_AMQPCPP_PATH \
            $GITHUB_WORKSPACE
            make -j$(nproc)
      - name: Install AMS ENABLE_CUDA=On ENABLE_CALIPER=${{ matrix.with_caliper }} ENABLE_MPI=${{ matrix.with_mpi }}
        run: |
          . /home/ams/venv/bin/activate
          cd build
          make -j$(nproc) install

  install-link-cpu-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/llnl/ams-ci-almalinux8:latest
      options: --user root

    strategy:
      matrix:
        with_shared: [ON, OFF]
    steps:
      - uses: actions/checkout@v7
      - name: Ensure git safe directory
        run: git config --global --add safe.directory '*'
      - name: Build SharedLibray=${{ matrix.with_shared }}
        shell: bash -l {0}
        run: |
          source /etc/profile
          module load gcc/13.3.1 mpi/openmpi-x86_64

          rm -rf build/
          mkdir -p build
          cd build
          
          cmake \
            -DBUILD_SHARED_LIBS=${{ matrix.with_shared }} \
            -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=${{ matrix.with_shared }} \
            -DCMAKE_INSTALL_PREFIX=$AMS_INSTALL_PATH \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_RMQ=On \
            -DENABLE_CALIPER=On \
            -DENABLE_CUDA=Off \
            -DENABLE_MPI=On \
            -DENABLE_TESTS=On \
            -DAMS_ENABLE_DEBUG=Off \
            -DENABLE_WORKFLOW=Off \
            -DTorch_DIR=$AMS_TORCH_PATH \
            -Dcaliper_DIR=$AMS_CALIPER_PATH \
            -DAMS_FMT_DIR=$AMS_FMT_DIR \
            -DHDF5_DIR=$AMS_HDF5_PATH \
            -Dnlohmann_json_DIR=$AMS_NLOHMANN_JSON_DIR \
            -Dtl-expected_DIR=$AMS_TL_EXPECTED_DIR \
            -Damqpcpp_DIR=$AMS_AMQPCPP_PATH \
            $GITHUB_WORKSPACE
            make -j$(nproc)
            make -j$(nproc) install
            echo "AMS_INSTALL_PATH=${AMS_INSTALL_PATH}"
            echo "AMS_INSTALL_PATH=${AMS_INSTALL_PATH}" >> $GITHUB_ENV

  install-link-cuda-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/llnl/ams-ci-cuda12.9.1:latest
      options: --user root
    strategy:
      matrix:
        with_shared: [ON, OFF]
    steps:
      - uses: actions/checkout@v7
      - name: Ensure git safe directory
        run: git config --global --add safe.directory '*'
      - name: Build SharedLibray=${{ matrix.with_shared }}
        shell: bash -l {0}
        run: |
          . /home/ams/venv/bin/activate
          rm -rf build/
          mkdir -p build
          cd build
          export AMS_INSTALL_PATH=$(pwd)/install
          echo "AMS_INSTALL_PATH=${AMS_INSTALL_PATH}"
          echo "Current directory is: $(pwd)"
          cmake \
            -DBUILD_SHARED_LIBS=${{ matrix.with_shared }} \
            -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=${{ matrix.with_shared }} \
            -DCMAKE_INSTALL_PREFIX=$AMS_INSTALL_PATH \
            -DENABLE_CALIPER=On \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_CUDA=On \
            -DENABLE_RMQ=Off \
            -DENABLE_MPI=Off \
            -DENABLE_TESTS=On \
            -DAMS_ENABLE_DEBUG=On \
            -DENABLE_WORKFLOW=Off \
            -DTorch_DIR=$AMS_TORCH_PATH \
            -Dcaliper_DIR=$AMS_CALIPER_PATH \
            -DAMS_FMT_DIR=$AMS_FMT_DIR \
            -DHDF5_DIR=$AMS_HDF5_PATH \
            -Dnlohmann_json_DIR=$AMS_NLOHMANN_JSON_DIR \
            -Dtl-expected_DIR=$AMS_TL_EXPECTED_DIR \
            $GITHUB_WORKSPACE
            make -j$(nproc)
            make -j$(nproc) install
            echo "AMS_INSTALL_PATH=${AMS_INSTALL_PATH}" >> $GITHUB_ENV
            ls ${AMS_INSTALL_PATH}
      - name: Build BOptions SharedLibray=${{ matrix.with_shared }}
        shell: bash -l {0}
        run: |
          . /home/ams/venv/bin/activate
          mkdir -p build_bnm_opt/
          cd build_bnm_opt/
          cmake \
            -DAMS_DIR=${AMS_INSTALL_PATH}/lib/cmake/AMS \
            -DCMAKE_PREFIX_PATH=${AMS_INSTALL_PATH} \
            $GITHUB_WORKSPACE/examples/bnm_opt/
          make -j$(nproc) VERBOSE=1

  build-rmq-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3.11
        env:
          RABBITMQ_DEFAULT_USER: ams
          RABBITMQ_DEFAULT_PASS: ams
        ports:
          - 5672

    container:
      image: ghcr.io/llnl/ams-ci-almalinux8:latest
      options: --user root
      env:
        RABBITMQ_USER: ams
        RABBITMQ_PASS: ams
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: 5672
    steps:
      - uses: actions/checkout@v7
      - name: Ensure git safe directory
        run: git config --global --add safe.directory '*'
      - name: Build RMQ=On AMS
        shell: bash -l {0}
        run: |
          source /etc/profile
          module load gcc/13.3.1 mpi/openmpi-x86_64

          python3 -m venv ci-venv
          source ci-venv/bin/activate
          rm -rf build/
          mkdir build
          cd build
          echo """{
                \"rabbitmq-user\": \"${RABBITMQ_USER}\",
                \"rabbitmq-password\": \"${RABBITMQ_PASS}\",
                \"service-port\": ${RABBITMQ_PORT},
                \"service-host\": \"${RABBITMQ_HOST}\",
                \"rabbitmq-vhost\": \"/\",
                \"rabbitmq-queue-physics\": \"test-ci\",
                \"rabbitmq-exchange-training\": \"ams-fanout\",
                \"rabbitmq-key-training\": \"training\"
              }""" > rmq.json
          jq < rmq.json
          export AMS_RMQ_CONFIG=$(cat ./rmq.json)
          cmake \
            -DBUILD_SHARED_LIBS=On \
            -DCMAKE_PREFIX_PATH=. \
            -DCMAKE_INSTALL_PREFIX=./install \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_CALIPER=On \
            -DENABLE_CUDA=Off \
            -DENABLE_MPI=Off \
            -DENABLE_TESTS=On \
            -DAMS_ENABLE_DEBUG=On \
            -DENABLE_WORKFLOW=On \
            -DAMS_INSTALL_FLUX_PYTHON=On \
            -DENABLE_RMQ=On \
            -DTorch_DIR=$AMS_TORCH_PATH \
            -Dcaliper_DIR=$AMS_CALIPER_PATH \
            -DAMS_FMT_DIR=$AMS_FMT_DIR \
            -DHDF5_DIR=$AMS_HDF5_PATH \
            -Dnlohmann_json_DIR=$AMS_NLOHMANN_JSON_DIR \
            -Dtl-expected_DIR=$AMS_TL_EXPECTED_DIR \
            -Damqpcpp_DIR=$AMS_AMQPCPP_PATH \
            $GITHUB_WORKSPACE
            make
      - name: Run tests RMQ=On AMSlib RabbitMQ egress
        run: |
          source /etc/profile
          module load gcc/13.3.1 mpi/openmpi-x86_64

          source ci-venv/bin/activate
          cd build
          # We overwrite the rmq.json created by CMake
          ctest --output-on-failure ./
        env:
          RABBITMQ_USER: ams
          RABBITMQ_PASS: ams
          RABBITMQ_HOST: rabbitmq
          RABBITMQ_PORT: 5672

  sqlite-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/llnl/ams-ci-flux-mariadb:latest
      options: --user root
    steps:
      - uses: actions/checkout@v7
      - name: Ensure git safe directory
        run: git config --global --add safe.directory '*'
      - name: Install AMS package (editable)
        shell: bash -l {0}
        run: |
          source /venv/bin/activate
          pip install -e ./
      - name: Run AMS unittests (SQlite)
        shell: bash -l {0}
        run: |
          source /venv/bin/activate
          python -m unittest discover -s tests/AMSWorkflow -p "test_*.py" -v

  mariadb-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/llnl/ams-ci-flux-mariadb:latest
      options: --user root
    steps:
      - uses: actions/checkout@v7
      - name: Ensure git safe directory
        run: git config --global --add safe.directory '*'
      - name: Start MariaDB
        shell: bash -l {0}
        run: |
          mysqld_safe --datadir=/var/lib/mysql &
          echo "Waiting for MariaDB..."
          until mysqladmin ping -h 127.0.0.1 --silent; do sleep 1; done
          echo "MariaDB is up"

      - name: Install AMS package (editable)
        shell: bash -l {0}
        run: |
          source /venv/bin/activate
          pip install -e ./

      - name: Run AMS unittests (MariaDB)
        env:
          AMS_DB_URL: "mysql+mysqlconnector://testuser:testpass@127.0.0.1/testdb"
        shell: bash -l {0}
        run: |
          source /venv/bin/activate
          python -m unittest discover -s tests/AMSWorkflow -p "test_*.py" -v
