name: Deploy containers

on:
  workflow_dispatch:

jobs:
  deploy-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push almalinux8 container
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          file: .github/containers/x86_64-broadwell-gcc11.2.1/Dockerfile
          push: true
          provenance: false
          tags: ghcr.io/LLNL/ams-ci-almalinux8:latest

      - name: Build and push cuda container
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          file: .github/containers/x86_64-broadwell-cuda11.6.1/Dockerfile
          push: true
          provenance: false
          tags: ghcr.io/LLNL/ams-ci-cuda11.6.1:latest
